# Generated by Django 4.2.6 on 2024-03-11 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website_owner',
            name='user',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(16), django.core.validators.RegexValidator('^[a-zA-Z0-9]{8,16}$', message='User must be 8-16 characters long and contain only letters and numbers.')]),
        ),
    ]
